[workspace]

resolver = "2"

members = [
    "cosmic-settings-daemon",
    "geoclue2",
    "hostname1",
    "locale1",
    "mpris2",
    "networkmanager",
    "switcheroo-control",
    "timedate",
    "upower",
    "bluez",
]

[workspace.dependencies]
futures-util = "0.3.30"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
time = { version = "0.3", features = ["parsing"] }
zbus = { version = "4.2.1" }
zvariant = { version = "4.1.0" }
